/**
 * Type declaration for Amplify outputs JSON file.
 * This file is auto-generated by AWS Amplify during deployment.
 */
declare module '*/amplify_outputs.json' {
  import { ResourcesConfig } from 'aws-amplify';
  const outputs: ResourcesConfig;
  export default outputs;
}
